use mathe_jung_alt;

CREATE OR REPLACE VIEW mathe_jung_alt.VW_RAETSEL_AUFGABENSAMMLUNGEN
AS
select
	a.UUID as ID,
	s.UUID AS SAMMLUNG_ID,
	s.NAME AS SAMMLUNG_NAME,
	s.SCHWIERIGKEITSGRAD,
	s.FREIGEGEBEN,
	s.PRIVAT,
	s.OWNER as SAMMLUNG_OWNER,
	a.NUMMER AS ELEMENT_NUMMER,
	a.PUNKTE AS ELEMENT_PUNKTE,
	r.UUID AS RAETSEL_ID,
	r.SCHLUESSEL AS RAETSEL_SCHLUESSEL
from
	AUFGABENSAMMLUNGSELEMENTE a,
	RAETSEL r,
	AUFGABENSAMMLUNGEN s
where
	a.RAETSEL = r.UUID
	and a.SAMMLUNG = s.UUID
	order by s.NAME;

