ALTER TABLE RAETSEL DROP COLUMN ADAPTIERT;

INSERT INTO DESKRIPTOREN (NAME, ADMIN, KONTEXT) VALUES ('Zitat', 1, 'QUELLEN');
INSERT INTO DESKRIPTOREN (NAME, ADMIN, KONTEXT) VALUES ('adaptiert', 1, 'QUELLEN');
