INSERT INTO mathe_jung_alt.QUELLEN (UUID, SORTNR, ART, PERSON, DESKRIPTOREN)
VALUES ('8ef4d9b8-62a6-4643-8674-73ebaec52d98', 1, 'PERSON', 'Heike Winkelvoß', (select ID from DESKRIPTOREN WHERE NAME = 'Person'));

CREATE OR REPLACE VIEW mathe_jung_alt.VW_QUELLEN
AS
SELECT q.UUID, q.SORTNR, q.ART, m.UUID as MEDIUM_UUID,  m.TITEL AS MEDIUM_TITEL, q.AUSGABE, q.JAHRGANG, q.SEITE, q.PERSON, q.DESKRIPTOREN
FROM mathe_jung_alt.QUELLEN q LEFT OUTER JOIN MEDIEN m ON q.MEDIUM = m.UUID;
