
ALTER TABLE QUELLEN DROP COLUMN HW;

ALTER TABLE QUELLEN ADD COLUMN USER_ID varchar(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci COMMENT 'Falls Person, dann deren UUID';

CREATE OR REPLACE VIEW mathe_jung_alt.VW_QUELLEN
AS
SELECT q.UUID, q.SORTNR, q.ART, m.UUID as MEDIUM_UUID,  m.TITEL AS MEDIUM_TITEL, q.AUSGABE, q.JAHRGANG, q.SEITE, q.PERSON, q.USER_ID, q.DESKRIPTOREN
FROM mathe_jung_alt.QUELLEN q LEFT OUTER JOIN MEDIEN m ON q.MEDIUM = m.UUID;

CREATE OR REPLACE VIEW mathe_jung_alt.VW_AUFGABEN
AS
select
	r.UUID,
	r.SCHLUESSEL,
	r.ANTWORTVORSCHLAEGE,
	vq.art,
	vq.MEDIUM_TITEL,
	vq.SEITE,
	vq.AUSGABE,
	vq.JAHRGANG,
	vq.PERSON,
	vq.USER_ID,
	vq.DESKRIPTOREN
from
	RAETSEL r,
	VW_QUELLEN vq
where
	r.QUELLE = vq.UUID;

CREATE OR REPLACE VIEW mathe_jung_alt.VW_AUFGABEN
AS
select
	r.UUID,
	r.SCHLUESSEL,
	r.ANTWORTVORSCHLAEGE,
	r.NAME,
	e.NUMMER,
	e.PUNKTE,
	vq.ART as QUELLE_ART,
	vq.MEDIUM_TITEL,
	vq.SEITE,
	vq.AUSGABE,
	vq.JAHRGANG,
	vq.PERSON,
	vq.USER_ID,
	vq.DESKRIPTOREN
from
	RAETSEL r,
	RAETSELGRUPPENELEMENTE e,
	VW_QUELLEN vq
where
    e.RAETSEL = r.UUID
	AND r.QUELLE = vq.UUID;

