CREATE OR REPLACE VIEW mathe_jung_alt.VW_AUFGABEN
AS
select
	r.UUID,
	r.NAME,
	r.SCHLUESSEL,
	e.NUMMER,
	e.PUNKTE,
	e.GRUPPE,
	r.ANTWORTVORSCHLAEGE,
	vq.ART as QUELLE_ART,
	vq.MEDIUM_TITEL,
	vq.SEITE,
	vq.AUSGABE,
	vq.JAHRGANG,
	vq.PERSON,
	vq.USER_ID,
	vq.DESKRIPTOREN
from
	RAETSEL r,
	RAETSELGRUPPENELEMENTE e,
	VW_QUELLEN vq
where
    e.RAETSEL = r.UUID
	AND r.QUELLE = vq.UUID;
