FROM thomasweise/docker-texlive-full:latest

# RUN apt-get install -y libnetpbm10-dev

COPY deb/* /tmp/
COPY --chmod=766 deb/*.sh /tmp/
COPY latex/*.tex /doc/
COPY --chmod=766 latex/*.sh /doc/


# CMD ["bash"]
# ENTRYPOINT ["/bin/bash"]

