version: "3.7"

services:

  docker-latex-client:
    image: heike2718/docker-latex-client
    networks:
      - mja-network
    ports:
      - 9200:8080
    volumes:
      - /home/heike/test:/doc
    environment:
      - TZ=Europe/Berlin
    restart: on-failure:3
    command: ["java","-jar","/opt/latex-client.jar"]

networks:
   mja-network:

