version: "3.3"

services:

  docker-latex-client:
    image: heike2718/docker-latex-client
    deploy:
        resources:
            limits:
              memory: 512M
            reservations:
              memory: 128M
    networks:
      - mja-network
    ports:
      - 9200:8080
    volumes:
      - /home/drpwzrd/docker-volumes/latex/doc:/doc
    environment:
      - TZ=Europe/Berlin
    restart: on-failure:3
    command: ["java","-jar","/opt/latex-client.jar"]

networks:
   mja-network:

