LaTeX-Microservice
==================

Heike Winkelvoß
:Author Initials: HW
:toc:
:icons:
:numbered:
:website: https://mathe-jung-alt.de/
:toc-title: Inhaltsverzeichnis

.Über dieses Dokument
***********************************************************************************************
Dieses Dokument beschreibt, wie der LaTeX-Microservice deployed und verwendet werden kann.
***********************************************************************************************

Zweck
-----

Der LaTeX-Microservice stellt einen http-Service zur Transformation von LaTeX nach PDF oder png zur Verfügung.

*Achtung:* Der Microservice sollte besser nicht frei im Internet herumgurken, sondern im Rahmen einer sicheren Anwendung verwendet werden, die LaTeX- Injection- Angriffe zuverlässig verhindert.

Wenn ein LaTeX- File als sicher identifiziert wurde, wird dieses in einen Docker-Volume gelegt, auf welchen der LaTeX-Microservice Zugriff hat und die
gewünschte Transformation vornehmen kann.

Das Transformieren der LaTeX-Datei ist nicht threadsafe, d.h. die Anwendung, die den Microservice nutzt, muss sicherstellen, dass jedes *.tex- File immer nur von einem Thread im Zugriff ist.

Dockerimages
------------

Es werden 2 Dockerimages zur Verfügung gestellt.

docker-java-latex
~~~~~~~~~~~~~~~~~

Dieses Image ist eina Adaption von <https://github.com/thomasWeise/docker-texlive-full>.

Es verwendet (anders als das aktuelle Image) ubuntu:20.04 als Basis und erweitert dieses um *openjdk-17-jre-headless*, so dass neben LaTeX auch eine Java-Runtime zur Verfügung steht.

Falls jemand eine andere Java-Version benötigt, muss er das Image anpassen.

Leider dauert das Bauen des images sehr lange, weil ein Haufen Tex-Zeug installiert werden muss.

docker-latex-client
~~~~~~~~~~~~~~~~~~~

Dieses Image erweitert heike2718/docker-java-latex um 

* netbpm, damit im container das command pnm zur Verfügung steht, um aus ps-Files png-Files herauszuschneiden.
* die Fonts fblnord (Fibelschrift Nord) und fblsued (Fibelschrit Süd)
* shellscripts latex2png.sh sowie latex2pdf.sh 
* eine Java-Anwendung, die diese scripte mit einem LaTeX-File als Argument aufruft, um dieses in das gewünschte Format zu tranformieren. Der Aufruf wird mittels undertow als http-Service zur Verfügung gestellt.

Der Austausch der Files (.tex bwz. .png) erfolgt über ein gemountetes docker volume. In diesem müssen sich alle Ressourcen befinden, die der LaTeX-Compiler benötigt, beispielsweise Files, die per include importiert wwerden oder eps-Dateien, die als Grafiken eingebunden werden.

Der java-Service kann bei Bedarf angepasst oder ersetzt werden, um latex2pdf.sh bzw latex2png.sh anderweitig aufzurufen.


Bauen der Images
----------------

docker-java-latex
~~~~~~~~~~~~~~~~~

```
docker image build -t heike2718/docker-java-latex .
```

docker-latex-client
~~~~~~~~~~~~~~~~~~~

Zuerst muss mittels mvn package die latex-client.jar gebaut und ins Verzeichnis docker/docker-latex-client/deployment kopiert werden.

```
DOCKER_BUILDKIT=1 docker image build -t heike2718/docker-java-client .
```

Testen des Images
~~~~~~~~~~~~~~~~~

```
docker container run -it -v /home/heike/git/mathe-jung-alt/backend/testfiles:/doc --name latex --entrypoint=/bin/bash heike2718/docker-latex-client
```

```
docker container exec -it latex /bin/latex2png.sh test1
```

```
docker container exec -it latex /bin/latex2pdf.sh test1
```

Das File test1.tex muss dazu in dem docker-volume liegen, das beim Starten des containers gemounted wird. Dort liegt anschließend auch das Ergebnisfile test1.pdf oder test1.png

Java-LaTeX-Client
-----------------

Dies ist ein in java geschriebener minimalistischer http-Service (Microservice) under Verwendung von Undertow.

Er lauscht auf dem Port 8080. Der Port ist hardcodiert, kann aber sebstverständlich beim Start des docker containers auf einen beliebigen anderen Port gemappt werden.

Architekturidee und Sicherheitshinweise
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Die REST-API ist minimalistisch und verwendet *nicht* https, da in der Regel der Java-LaTeX-Client-Microservice nicht nach außen propagiert werden sollte. Außerdem gibt es lediglich 2 REST-Endpoints, die keine sensiblen Daten transportieren, sondern Commands im Container triggern, die auf LaTeX-Files arbeiten.

Die Architekturidee ist, den Java-LaTeX-Client-Microservice mittels docker compose in ein docker network zu integrieren, in dem er mit 

```
http://docker-latex-client:8080
```

aufgerufen werden kann (docker-latex-client ist der Name des service in der docker-compose.yml)

*Achtung:* Für die Input-Validierung des LaTeX-Codes ist der nach außen sichtbare Service zuständig. Dieser muss LaTeX-Injection zuverlässig abwehren, damit durch den Aufruf des Java-LaTeX-Client-Microservice kein Sicherheitsrisiko besteht.

Die zu transformierenden Files werden über einen gemeinsam genutzten Volume ausgetauscht. Das Zielverzeichnis im Container ist /doc. Also der nach außen sichtbare Service legt in /doc ein tex-File und ggf. andere Files wie images ab, ruft dann den Microservice zum Transformieren auf und sammelt das Ergebnisfile aus /doc wieder auf.


REST-API
~~~~~~~~

*Transformation LaTeX -> PDF:*

http://host:port/latex2pdf?filename=name-tex-file-ohne-suffix

*Transformation LaTeX -> PNG:*

http://host:port/latex2png?filename=name-tex-file-ohne-suffix


Content-Type ist application/json.

Das Antwort-Format ist dieses:

```
{
  "level": "INFO",
  "message": "fertig: execute command PDF on file 02819 - exitCode=0"
}
```
*Antworten*

* Level INFO: alles ok, transformiertes File liegt neben dem source-LaTeX-File.
* Level ERROR: Transformation konnte nicht erfolgen. Es steht dann etwas im Server-Log des docker-latex-client-Containers. Es gibt kein transformiertes File.

Testen des Images
~~~~~~~~~~~~~~~~~

docker container run -it -v /home/heike/git/mathe-jung-alt/backend/testfiles:/doc -p 8080:8080 --name latex heike2718/docker-latex-client

docker container run -it -v /media/veracrypt1/knobelarchiv_2/latex/temp:/doc -p 8080:8080 --name latex heike2718/docker-latex-client


Im docker-Volume liegt eine fehlerfrei compilierbare Datei test1.tex.

curl -X GET -i 'http://localhost:8080/latex2pdf?filename=test1'
curl -X GET -i 'http://localhost:8080/latex2png?filename=test1'

Testdateien
----------

unter [testfiles](./backend/testfiles) liegen 2 LaTeX- Files zum Testen.

* test1.tex ist ohne weitere Ressourcen in sich vollständig
* test2.tex testet die Verzeichnisstruktur und Referenzierungen, wenn per include oder image verschachtelt wird.
