REST API
========

Heike Winkelvoß
:Author Initials: HW
:toc:
:icons:
:numbered:
:website: https://mathe-jung-alt.de/
:toc-title: Inhaltsverzeichnis

.Über dieses Dokument
***********************************************************************************************
Dieses Dokument beschreibt, wie der Service verwendet werden kann.
***********************************************************************************************

Wozu ist es gut?
----------------

Der Service stellt REST-Endpoints zur Verfügung um LaTeX-Dateien nach png oder pdf zu transformieren.

Die Dateien müssen dazu zunächt in das konfigurierte Arbeitsverzeihchnis gelangen, ggf. zusammen mit Bildern etc.

Die Ergebnis-Datei liegt anschließend neben der source-Datei im Arbeitsverzeichnis.

Mögliches Zusammenwirken mit anderen Services: Austausch der Files über ein volume.


Konfiguration
-------------

Das Arbeitsverzeichnis wird mit der application-property path.external.files konfiguriert.

URLs
----

*lokal:*

* localhost:9100/latex/pdflatex?fileName=test1

Dieser Pfad transformiert die Datei test1.tex in eine Datei test1.pdf.


* localhost:9100/latex/latex2png?fileName=test1

Dieser Pfad transformiert die Datei test1.tex in eine Datei test1.png.

Docker
------

DOCKER_BUILDKIT=1 docker image build -t heik2718/latex .

docker container run -dit --name latexpoc -v /home/heike/git/mathe-jung-alt/backend/latexpoc/latex/:/doc/ --entrypoint=/bin/bash heik2718/latex

docker container run -dit --name latexpoc --entrypoint=/bin/bash heik2718/latex


docker run -v /home/heike/git/mathe-jung-alt/backend/latexpoc/latex/:/doc/ -t -i thomasweise/texlive

The following packages have unmet dependencies:
 openjdk-11-jre-headless:arm64 : Depends: ca-certificates-java:arm64 (>= 20190405~) but it is not installable
                                 Depends: java-common:arm64 (>= 0.28) but it is not installable
                                 Depends: libcups2:arm64 but it is not installable
                                 Depends: liblcms2-2:arm64 (>= 2.2+git20110628) but it is not installable
                                 Depends: libjpeg62-turbo:arm64 (>= 1.3.1) but it is not installable
                                 Depends: libfontconfig1:arm64 but it is not installable
                                 Depends: libnss3:arm64 (>= 2:3.17.1) but it is not installable
                                 Depends: libasound2:arm64 (>= 1.0.16) but it is not installable
                                 Depends: libc6:arm64 (>= 2.33) but it is not installable
                                 Depends: libfreetype6:arm64 (>= 2.3.5) but it is not installable
                                 Depends: libgcc-s1:arm64 (>= 4.0) but it is not installable
                                 Depends: libharfbuzz0b:arm64 (>= 1.2.6) but it is not installable
                                 Depends: libpcsclite1:arm64 (>= 1.3.0) but it is not installable
                                 Depends: libstdc++6:arm64 (>= 4.1.1) but it is not installable
                                 Depends: zlib1g:arm64 (>= 1:1.2.2) but it is not installable
E: Unable to correct problems, you have held broken packages.

