REST API
========

Heike Winkelvoß
:Author Initials: HW
:toc:
:icons:
:numbered:
:website: https://mathe-jung-alt.de/
:toc-title: Inhaltsverzeichnis

.Über dieses Dokument
***********************************************************************************************
Dieses Dokument beschreibt, wie der Service verwendet werden kann.
***********************************************************************************************

Wozu ist es gut?
----------------

Der Service stellt REST-Endpoints zur Verfügung um LaTeX-Dateien nach png oder pdf zu transformieren.

Die Dateien müssen dazu zunächt in das konfigurierte Arbeitsverzeihchnis gelangen, ggf. zusammen mit Bildern etc.

Die Ergebnis-Datei liegt anschließend neben der source-Datei im Arbeitsverzeichnis.

Mögliches Zusammenwirken mit anderen Services: Austausch der Files über ein volume.


Konfiguration
-------------

Das Arbeitsverzeichnis wird mit der application-property path.external.files konfiguriert.

URLs
----

*lokal:*

* localhost:9100/latex/pdflatex?fileName=test1

Dieser Pfad transformiert die Datei test1.tex in eine Datei test1.pdf.


* localhost:9100/latex/latex2png?fileName=test1

Dieser Pfad transformiert die Datei test1.tex in eine Datei test1.png.

Docker
------

DOCKER_BUILDKIT=1 docker image build -t heik2718/latex .

Das docker image basiert auf [thomasweise/docker-texlive-full](https://github.com/thomasWeise/docker-texlive-full) und installiert zusätzlich das paket netbpm. Außerdem enthält es 2 shell-scripts:

* /bin/latex2png.sh wandelt ein tex-File in ein png um
* /bin/latex2pdf.sh wandelt ein tex-File in ein pdf um

Das umzuwandelnde file nebst seinen dependecies muss im Verzeichnis /doc liegen. Dieses Verzeichnis kann als docker volume gemounted werden, so dass
eine andere Anwendung die tex- und image- Files dort ablegen und dann die skripte wie folgt verwenden kann:

docker container exec -it latexpoc /bin/latex2png.sh test1
docker container exec -it latexpoc /bin/latex2pdf.sh test1

Zuvor wird der conteiner gestartet mit

docker container run -dit -v /home/heike/git/mathe-jung-alt/backend/latexpoc/latex:/doc --name latexpoc --entrypoint=/bin/bash heik2718/latex


